export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  FACILITY_ADMIN = 'FACILITY_ADMIN',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  RECEPTIONIST = 'RECEPTIONIST',
  PHARMACIST = 'PHARMACIST',
  EQUIPMENT_STAFF = 'EQUIPMENT_STAFF',
  CRM_ANALYST = 'CRM_ANALYST',
}
